balena-os/leviathan

lib/workers/qemu.js

Without kvm qemu does not connects the vpn

Add kvm support to speed qemu up

---

lib/components/os/resinos.js
lib/components/resinio/sdk.js
lib/main.js
lib/workers/manual.js
lib/workers/qemu.js
tests/os-file-format.js

Create OS component which provides the required configuration to run a specific OS.
This class will be closely related (coupled) to the worker class. The ready method in the
worker class will use OS class to fetch and configure the image.
The two interfaces should be kept in sync.
We need for this component when trying to configure an OS which is specific to the OS
but must executed by the worker. If this component would not exists OS specific code
would exist in the worker.

Define OS concept

---

lib/components/resinio/sdk.js
lib/main.js

HostOS verison to be greater than 2.7.5 and the device to be connected to the vpn

ResinIO ssh connection requires a certain device state

---

package.json

This repo is one of the 16 repos identified to use/require a [resin-semver](https://github.com/resin-io-modules/resin-semver) version older than 1.4.0. See also:
* [Trello card](https://trello.com/c/11ZJfEv6/114-update-repos-that-depend-on-resin-semver)
* [Flowdock thread](https://www.flowdock.com/app/rulemotion/namechange/threads/lS-o4xF4qMvf-o2rAtdrqaZEPhs)

Update package.json for new resin-semver release

---

worker/lib/workers/testbot.ts

Previous implementation was not handling the thrown exception and
test was hanging instead of being terminated.
Example error: "Cannot find /dev/sda" (when SD card is missiing).

Fix error handling for the missing target drive

---

core/lib/main.js

We could not perform 2 test runs in a raw without restarting the core
because of the missing state update when suite is completed.
Before the change, the state was updated from /stop handler only.

Update the state when suite finishes

---

worker/lib/workers/nm.ts

A quick fix to ensure we fail fast if DBUS connection cannot be
initialized. Previously the test was hanging in this case.

Fail fast when dbus connection cannot be established

---

core/lib/common/worker.js

Regeexp is changed to a greedy one to handle lines like
error: ENOENT: not such file or directory

Fix flash error processing

---

.dockerignore
.gitignore
client/.dockerignore
client/.gitignore
client/Dockerfile
client/bin/multi-client.default.conf
client/bin/multi-client.js
client/bin/single-client.default.conf
worker/lib/index.ts
worker/lib/workers/testbot.ts
workspace/.gitignore
workspace/README.md
workspace/build-client.sh
workspace/run-tests.sh

Allows running the client as a docker container.
Also, introduces the workspace directory that should be used for local/dev runs.

Dockerize client

---

suites/os/suite.js

We need to review this test implementation and think if there is a more efficient way to do it.
Also, an ability to run short/long tests would be helpful.

Disable boot-splash test

---

suites/os/tests/config-json.js

Due to the flaky nature of the Persistent Logging test in the Leviathan test suite (being investigated in [meta-balena](https://github.com/balena-os/meta-balena/issues/1919)), the build frequently fails in Jenkins with no reason at all. 
Until the issue is resolved, the test execution is disabled.

Disable execution of Persistent Logging test

---

client/lib/index.js
core/lib/main.js

Previous version waas not handling errors reported by the on-device core service.
Also, avoid resetting the test suite in case of the init error in the core.

Fix error handling

---

suites/os/tests/config-json.js

- Reactivates previously disabled persistent logging test here #338 
- Patch permission denied error in DNS test. Reference below.
Reference:
- https://jenkins.dev.resin.io/job/leviathan-raspberrypi4-64/376/console (and other RPi builds)
- In context to: https://www.flowdock.com/app/rulemotion/device-testing/threads/HS7QbT8ghvW6il95FOqE4pMexc6

Patch Persistent logging & DNS tests

---

suites/os/tests/config-json.js

Disabling the persistent logging test again, 
Context: https://www.flowdock.com/app/rulemotion/device-testing/messages/35792

Disable persistent logging test

---

README.md

Getting Started section wasn't documented for Leviathan, added it along with the instruction to push releases to applications on BalenaCloud

Add Getting Started section to README

---

client/bin/multi-client.js
compose/balena.yml
core/lib/common/suite.js
documentation/Getting-started.md
worker/config/default.js
worker/lib/helpers/graphics.ts
worker/lib/index.ts
worker/lib/workers/testbot.ts
worker/typings/worker.d.ts

This PR re-enables the capability for screen capture. In this old PR (https://github.com/balena-os/leviathan/commit/276e24a815e1985c29f28ac3ee91c3289d10e547), the /select route of the worker was removed. This prevented the `screen` option from being passed to the worker object (e.g the testbot worker object), which meant the screen capture could not be enabled.
This PR is required in order to run the HDMI boot-splash test

fix hdmi capture

---

core/lib/components/balena/cli.js
core/lib/components/balena/sdk.js
documentation/Getting-started.md

adds several helpers to `lib/components/sdk.js` intended to help with tests involving balena cloud
- push to application
- wait until services running
- get supervisor version
- execute command in container

Add cloud helpers

---

core/lib/components/balena/sdk.js

We have had multiple tests that use the /core/components/sdk.js `waitUntilServicesRunning()` function fail when running on the RPi0 because the device is slow, and was thus exceeding the ~10 minute timeout (20 tries, 30 seconds apart) that was hard coded into this function. 
This fix allows the user of the function to configure the number of retries.

make timeout on waitUntilServicesRunning() configurable

---

client/bin/multi-client.js
client/lib/index.js
core/lib/main.js

We were often seeing an error during the upload of images from clients to workers. After a long investigation in to why, I think that the following was the problem:
1. core asks for image, client receives that request
2. client responds by sending image
3. in core, if there is a connection problem, the stream is closed. 
4. an error is created in core, and it tries to signal this to the client - this message never made it back to the client, because the stream was closed - therefore the client never attempted to retry
5. There was no mechanism for the core to know that it had failed the transfer of the image, so it requested the next artifact
So mainly there were 2 problems:
1. if an error happened during the transfer of the image, related to the stream closing early, there was no way to …

Make changes to upload retry mechanism

---

core/lib/common/worker.js

In a test here: https://jenkins.dev.resin.io/job/leviathan-raspberry-pi/741/console
We seemed to have a socket-hang up error when trying to make a get request to the supervisor to fetch a container ID. This PR makes sure that the retry that is is place doesn't throw if we can't contact the supervisor, and tries again. 

Prevent throwing errors in waitUntil of pushContainerToDUT helper

---

client/bin/multi-client.js

This adds timestamps to logs recieved by the client. Example output:
```
[2021-06-18T15:36:18.953Z][af82ff1-os] found 0 vulnerabilities
[2021-06-18T15:36:19.004Z][af82ff1-os] Removing artifacts from previous tests...
[2021-06-18T15:36:20.066Z][af82ff1-os] Run queue summary:
[2021-06-18T15:36:20.067Z][af82ff1-os]  Unmanaged BalenaOS release suite
[2021-06-18T15:36:20.067Z][af82ff1-os]   OS corruption tests
[2021-06-18T15:36:20.068Z][af82ff1-os]           resinos.fingerprint file test
[2021-06-18T15:36:20.068Z][af82ff1-os]   OS-release tests
[2021-06-18T15:36:20.068Z][af82ff1-os]           OS-release file check
[2021-06-18T15:36:20.068Z][af82ff1-os]   chrony tests
```

add log timestamping

---

core/config/default.js
core/lib/common/suite.js
core/lib/common/test.js
core/lib/common/worker.js
core/lib/components/balena/sdk.js
core/lib/components/os/balenaos.js

Previously the `balenaOS` class was only usable with the image that is sent from a client. In cases where users want to download an image instead it wasn't simple to use. 
This PR allows users to provide a custom path to an OS image when creating an instance of the object.
For example, when using the OS image that is sent from the client: 
```js
this.suite.context.set({
os: new BalenaOS(
{
deviceType: this.suite.deviceType.slug,
network: this.suite.options.balenaOS.network,
configJson: {
uuid: this.suite.options.balenaOS.config.uuid,
os: {
sshKeys: [
await this.context
.get()
.utils.createSSHKey(this.context.get().sshKeyPath),
],
},
// persistentLogging is managed by the supervisor and only read at first boot
persistentLogging: true,
// Set local mode so we can perform local pushes of …
```

Generalise os helpers

---

core/lib/common/utils.js

waitUntil is a helper that runs a function for a designated number of times till it satisfies a particular condition to break out of the loop. In the current implementation, if `rejectionFail` is `true` and if the command fails to satisfy the condition in an iteration then the `waitUntil` helper returns an error which isn't quite helpful for a function that is meant to continuously wait until something is complete. Hence, the change to make `rejectionFail` as default to `false` in the `waitUntil` helper

patch: Update waitUntil helper's rejection condition to default false

---

core/config/default.js
core/lib/components/balena/cli.js

In PR #433 we made the unpacking functions unpack the image to a directory that is automatically deleted at the end of a test suite. This broke the preload helper function, which required the image to be in a volume to work

fix preload helper

---

.dockerignore
README.md
core/lib/common/archiver.js
core/lib/common/context.js
core/lib/common/graphics.js
core/lib/common/state.js
core/lib/common/suite.js
core/lib/common/teardown.js
core/lib/common/test.js
core/lib/common/utils.js
core/lib/common/worker.js
core/lib/components/balena/cli.js
core/lib/components/balena/sdk.js
core/lib/components/balena/sync.js
core/lib/components/balena/utils.js
core/lib/components/os/balenaos.js
core/package-lock.json
core/package.json
core/pagesconfig.json
core/tsconfig.json
documentation/config-reference.md
documentation/getting-started.md
documentation/learn-more.md
documentation/quickstart.md
documentation/reference-tips.md
documentation/writing-tests.md
package.json

Took time and head banging but I have successfully, 
- Redocuments helpers 
- Rearranges already written documentation
- Create helper specific documentation pages
- Setup Typedoc for documenting future helpers
The only thing left to do
Almost there on this one
Explanation: We are using a typedoc plugin that lets us have the sidebar the way it is but the plugin hasn't been updated for quite a while. So if losing search isn't okay then we might be losing the sidebar. This is the plugin - https://github.com/mipatterson/typedoc-plugin-pages, already pinged on open issues there. 
Added these instructions on the README + the documentation would be available on GitHub pages

Document Leviathan Helpers

---

client/bin/multi-client.js
client/lib/balena.ts

Previously, when selecting available workers by the DUT tag and the list contained 2 or more workers. The logic was only testing one testbot if it was online or not. If it wasn't online that that testbot was removed from the list, and other testbots weren't being checked which lead to 503 errors when those testbots were being reached for jobs. 
We debugged and fixed that by identifying that we were hot-fixing/modifying the array while iterating through it as well. This was the reason behind inconsistencies which were fixed creating a new array for selectedDevices and returning that as the list of viable workers. 
The PR also includes:
1. Adding an ISO timestamps to INFO messages and not just workerLog messages.
2. Improving the error thrown when state can't be retrieved from testbots with …

patch: Fix grouping of online testbots when selecting available workers

---

core/lib/components/balena/cli.js

In the constructor for the CLI class, we are now setting the `BALENARC_BALENA_URL=${API_ENVIRONMENT}` variable to set the API environment for the CLI. 
﻿Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

patch: CLI helpers considerate of API environment

---

core/lib/main.js

If you set the env variable `LOCAL=local` then you can stop the core from requesting images and tests to be uploaded from the client

enable testing without client uploads

---

client/lib/index.js

This is to help us debug when the client hangs after a suite is supposedly finish 

add message when suite exits to client

---

client/lib/index.js

When the image specified in config.js does not exist, the
single-client.js script exits with no failures, and no logged errors.
Catch this error and log it to the console.

client: log error message when image does not exist

---

core/lib/common/suite.js
core/lib/common/worker.js

The archiverLogs helper doesn't work at the moment, will need some discussion on how we need to implement it. IF we want to implement it.

Restructure teardown order to prevent dependency issues

---

core/lib/common/utils.js

During some hup tests we are getting a keepAlive timeout while waiting for a HUP to finish - so this is an attempt to stop that from happening

increase ssh keepalive interval time

---

client/package.json

This is to make the test summary generation work.  Babel node documentation says not to use in production anyway

disable bable-node

---

worker/Dockerfile.template

This will reduce the size of the container, and will also remove an error we were getting when trying to create a new release

remove redundant parts of worker dockerfile

---

core/lib/common/suite.js

When tests fail the test suite continues, even though the PR will be blocked anyway, wasting a lot of time. In this PR I use the bail flag to signal that the tests should bail after the first failure.
Discussed here: https://www.flowdock.com/app/rulemotion/r-resinos/threads/oBsi97NTPDBl5iiRPq_MaleiV4A

have test suite bail after first failure

---

core/Dockerfile.template
core/lib/components/balena/cli.js

- Updating balena-cli to unblock `balena preload` on ARM devices. 
- Bringing fleet to leviathan - Fewer warnings, clearer output

Update balena-cli to 12.48.0 

---

core/lib/state.js

Existing code attempts to ignore failures opening LED file paths in
safeWrite(). However, there's an unhandled promise rejection in a couple
of places as a result of mishandling the rejection. Catch the error to
prevent this warning.

core: handle promise rejection in state

---

core/lib/common/suite.js
core/lib/common/worker.js
core/lib/components/os/balenaos.js

This enables you to set an env variable on the worker called `DEBUG_KEEP_IMAGE=true`, and then the test suite won't delete the unpacked and configured image at the end of the tests.
This allows you to then comment out the flash + configure steps in your test suite to quickly run the tests again without flashing

allow option to keep image post test

---

Makefile
worker/Dockerfile.template

This change is required for variable substitution in the Dockerfile templates after replacing `BALENA_MACHINE_NAME` with `BALENA_ARCH` in https://github.com/balena-os/leviathan/pull/518

Makefile: replace BALENA_ARCH in Dockerfile templates

---

compose/balena.yml
core/lib/common/suite.js
core/lib/common/worker.js
worker/lib/index.ts
worker/package-lock.json
worker/package.json
worker/tsconfig.json

This change creates a "contract" within the worker container - a json object that is populated based on tags placed on the worker device via the cloud. This contract is exposed via a http endpoint (`/contract`). At the moment, it only has 3 fields:
```json
{
"dut": "raspberrypi3",
"screencapture": true,
"modem": false
}
```
That can be set using tags on the device of the same name. (e.g setting a tag `screencapture: true` on the worker will set that in the contract. It can be extended by adding to the `supportedTags` array in `worker/lib/index.ts
##################
Within a test suite, a `workerContract` object can be created:
```js
// Get worker setup info
this.suite.context.set({
workerContract: await this.context.get().worker.getContract()
})
```
And then at the top of a test, you can …

add worker contract

---

core/lib/common/utils.js
core/lib/common/worker.js
core/lib/components/balena/sdk.js
workspace/.gitignore

Reduce retries counters and timeouts on waitUntil and executeCommandIntoHostOS for faster outcomes and less waiting. 
﻿Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

patch: Reduce helpers delays and retries

---

worker/lib/workers/qemu.ts

Fix returning a promise from setupBridge() that never resolves.

worker: qemu: fix unresolved promise in setupBridge()

---

worker/Dockerfile.template

With the merge of https://github.com/balena-os/meta-balena/pull/2364, @jakogut has moved the glider dependency from the Worker framework to the actual test where it's needed. This will make the Worker Dockerfile lighter and faster

patch: Remove nadoo/glider from Dockerfile

---

client/bin/multi-client.js
client/lib/index.js
compose/generic-x86.yml
core/Dockerfile.template

This PR fixes 2 problems:
- when using the qemu worker, erroneous `Test suite has exited with: FAIL` messages were coming up while "flashing"
- When the `workspace/config.js` file had multiple suites targetting the same worker url, both suites would try to run at the same time on the same worker

Make fixes to client to improve usage with qemu worker

---

core/lib/common/utils.js
core/lib/common/worker.js
core/lib/components/balena/sdk.js
workspace/.gitignore

Reverts balena-os/leviathan#488
It appears that the current HUP suite in meta-balena at the revision below, do not have a long enough timeout to detect the DUT is online after flashing. I've testing with latest leviathan and the tip of meta-balena test suites with raspberrypi3.
https://github.com/balena-os/meta-balena/tree/cab2b5aa7b97afad9006ed3c3701e49a9d76d366/tests/suites/hup
```
[2021-11-21T18:14:17.357Z][192-hup] Powering off DUT
[2021-11-21T18:14:17.454Z][192-hup] Preparing to flash
[2021-11-21T18:17:49.918Z][192-hup] Flash completed
[2021-11-21T18:17:49.930Z][192-hup] Powering on DUT
[2021-11-21T18:17:51.495Z][192-hup] DUT powered on
[2021-11-21T18:17:51.505Z][192-hup]         # Waiting for DUT to be reachable
[2021-11-21T18:18:40.659Z][192-hup]         not ok 1 - 500 - "Could not …
```

Revert "patch: Reduce helpers delays and retries"

---

worker/lib/workers/qemu.ts

Dnsmasq can be configured (and already is) to only listen on specific
interfaces—for DHCP. By default, it will still listen on port 53 for DNS
queries, which makes it impossible to run multiple instances
concurrently.
From the man page:
-p, --port=<port>
Listen on <port> instead of the standard DNS port (53). Setting this to
zero completely disables DNS function, leaving only DHCP and/or TFTP.
Specify --port=0 to disable DNS, and allow multiple instances to run
concurrently.

qemu: network: disable dnsmasq DNS server

---

worker/lib/index.ts

When we removed the dependency on glider in the proxy tests, we also
removed glider from the worker. However, older versions of the tests
from ESR branches would still call this endpoint and expect a sane
response.
Fortunately, the old proxy tests were invalid and would always pass
even if glider wasn't working. ICMP traffic does not use the proxy.
So, we can just pretend to start a glider instance so the old tests
continue to run, even with an invalid result.
See: https://github.com/balena-os/leviathan/pull/534

Stub the proxy endpoint as glider has been removed from the worker

---

worker/Dockerfile.template
worker/lib/workers/qemu.ts

This puts the "required" iptables rules set up into the worker set up code, along with the appropriate teardowns. It also removes the bridge interface we create as part of the teardown.
These changes are needed to allow us to run the worker in jenkins instances cleanly

worker: set up iptables and cleanup in teardown

---

Makefile

`make detached` throws an error because the detached flag is at the end of the docker-compose command. Moved it to the right place so no errors get thrown.

makefile: fix detached flag in make detach

---

client/lib/index.js
core/config/default.js
docker-compose.local.yml
worker/config/default.js

This allows you do set the ports that core+worker listen on via env vars, pre-req for multiple qemu workers on same host
See: https://github.com/balena-os/leviathan/issues/561

allow setting of ports via env var

---

worker/config/default.js
worker/lib/helpers/index.ts
worker/lib/workers/qemu.ts
worker/package-lock.json
worker/package.json
worker/typings/worker.d.ts

Set up the bridge parameters for the qemu worker dynamically. This is to avoid conflicts when multiple workers + qemu instances are running on the same host. 
The following are dynamically generated instead of being hardcoded/set with env variables:
- bridge name
- bridge ip 
- dnsmasq dhcp range
- qemu vnc port
- qemu qmp port
Required-by: https://github.com/balena-os/leviathan/pull/568

worker: set up bridge parameters dynamically

---

client/lib/index.js
core/Dockerfile.template
core/lib/common/suite.js
core/lib/main.js

The NPM cache for RPi0 got corrupted which lead to NPM errors: https://www.flowdock.com/app/rulemotion/device-testing/threads/Oa9Ewh7FqSTu0OR_XAGqOzPbxxg
Adding a `npm cache clear` in order to clean cache before each test run.
﻿Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

patch: Clear cache when test starts

---

.github/workflows/links.yml
lychee.toml

Current link checker doesn't have a easy way to exclude private repository links. 
Going in with the trusted Lychee

patch: Replace link-checker with Lychee

---

worker/entry.sh

See: https://github.com/balena-os/leviathan/pull/579

worker: Avoid running QEMU entrypoint cmds on testbot

---

client/lib/index.js
core/lib/common/suite.js

This way is the only way (IMHO) to not create a massive breaking change but also be able to deprecate the use of conf.js
It's stealthily cutting out the middle man that is conf.js in test suites which has been confusing us for some time now. 

minor: Deprecate the use of conf.js in test suites

---

core/lib/components/balena/cli.js
docker-compose.local.yml

These changes enable the preload helpers to be used when running leviathan containers in the emulated test scenario. 
- Share host docker socket with core container (required for preloader)
- Modify prelaoder helper function to correctly find the path of the image 

fix preloading helpers for qemu worker

---

worker/bin/index.ts

Previously, the worker would exit with an error if the server address
was a string, instead of an object describing a TCP socket.
Unfortunately, a string is a valid address in the case of listening to a
UNIX domain socket. Remove this error condition, as the server will
raise an error anyway if the port cannot be used.

worker: allow listening from UNIX domain socket path

---

worker/lib/workers/qemu.ts
worker/typings/worker.d.ts

QEMU can accept firmware blobs for different architectures, machine
types, and feature sets (e.g., secure boot). OVMF is a commonly
available firmware implementing the UEFI specification for virtual
machines based on edk2.
Various distributions package and ship OVMF firmware, but with varying
paths between them. Allow for user defined paths to firmware files,
instead of a static path.
Additionally, add a method to automatically find firmware when no path
is specified.

QEMU Firmware options

---

core/lib/components/os/balenaos.js

The BalenaOS object has a fetch() method that unpacks a compressed disk
image from an input path to a destination path, called "path". The
destination is currently pulled from a config file.
We don't need to retain the extracted image, so switch to a temp file
path, which makes this bit of configuration unnecessary.

core: balenaos: use temp file for image path

---

worker/bin/index.ts
worker/lib/helpers/index.ts
worker/lib/index.ts

Add Leviathan.RuntimeConfiguration as a parameter to setup(), allowing
reuse of this function to create and run Worker servers without a config
file.

worker: add runtimeConfiguration as parameter to setup()

---

core/lib/common/test.js

The Test object is constructed with a Suite instance, which is
accessible from inside tests using 'this.suite'. However, another object
is created using only certain properties from the input suite object.
Remove the intermediate object so that all properties from the suite
object are exposed in the test code.

core: test: remove intermediate suite object

---

core/lib/common/suite.js
core/lib/common/taskQueue.js

Refactor Teardown class as TaskQueue to facilitate registering tasks for
setup as well as teardown. A separate Teardown object inherits from
TaskQueue and retains the signal handling from the original object.
This is a precursor to separating the forking behavior from the suite
object in preparation for having a standalone runner for virtualized
workers. For example, we can move the removeDownloads hook from the
Suite object to a separate SuiteSubprocess object that is specifically
for handling suites not running on a the same physical machine.

core: refactor Teardown as TaskQueue

---

worker/lib/index.ts

Get workerType from runtimeConfiguration, obviating the need for the
config module.

worker: get workerType from runtimeConfiguration

---

.github/workflows/balena-ci.yml

These extra tags create a lot of noise on busy repositories.
Also enable versionbot for proper forward-versioning.

Disable tagging by the deploy-to-balena-action

---

core/lib/common/state.js

The suite module sends log messages to the parent process when it's
forked using process.send(). When the suite module is not forked, this
results in a TypeError, as process.send is undefined.
Check that process.send is not undefined before attempting to call it.

core: state: fix TypeError when not running as a subprocess

---

core/lib/common/utils.js

This fixes the error:
any-promise is already defined as "global.Promise"
When running a suite in-proc.

core: utils: replace any-promise with native

---

core/lib/common/suite.js
core/lib/components/balena/cli.js
core/lib/components/balena/sdk.js

~~Looking for help on this, I only added the API env support to the SDK constructor because if I added it to both CLI and SDK then the file was being modified twice. Constructor can't be async so in a synchronous loop, both constructors for CLI and SDK run together and end up modifying the file twice. Hence, I had to give up and add this to the SDK only.~~ 
Okay thought this through, found a better way to do it. 

patch: Support staging environment for balenaCLI

---

core/lib/common/worker.js

This allows users to pass commands to worker.executeCommandInHostOS() as
arrays and have the elements be joined by spaces into a string before
execution. This allows for better styling with line breaks, etc. without
explicitly adding a join to the array.

core: worker: join command arrays with spaces

---

worker/lib/workers/qemu.ts

Workers have an option to override the disk image path used, but this
was ignored in the qemu worker. Fix it to use this option when present.

worker: qemu: fix worker image path

---

core/lib/common/test.js

Return a proxy of this object that will forward access to properties
present in the context object to that object.
This allows us to shorten, e.g.:
`this.context.get().worker.executeCommandInHostOS(...)`
To just:
`this.worker.executeCommandInHostOS(...)`
Also:
`this.context.get().worker.rebootDut(this.context.get().link)`
Becomes simply:
`this.worker.rebootDut(this.link)`

core: test: proxy context to shorten test code

---

worker/config/default.js
worker/lib/helpers/nm.ts
worker/lib/index.ts
worker/lib/workers/qemu.ts
worker/lib/workers/testbot.ts
worker/typings/worker.d.ts

These objects contain a lot of the same configuration, yet are subtlely
divergent for no apparent reason. Merge them into RuntimeConfiguration
and replace all references with the new object.

worker: merge Leviathan Options and RuntimeConfiguration

---

worker/Dockerfile.template

FD context: https://www.flowdock.com/app/rulemotion/p-testbot/threads/ZU9ant6-VdGwrp7mzEn5WVn13NZ
﻿This reverts commit 398474b5ac9e894152ea9a99a8a851462c3b0343.

Revert "worker: use nodejs package from upstream alpine"

---

worker/lib/index.ts

Older TS versions typed objects passed to exception handlers as `any`,
regardless of the fact that it's not guaranteed these objects inherit
from the Error prototype. Newer TS versions throw an error because the
type is unknown:
worker/lib/index.ts:282:25 - error TS2571: Object is of type 'unknown'.
Fix this error by checking that the object passed to the error handler
is indeed an instance of Error before accessing the message property.

worker: fix TS2571 error in exception handler

---

client/bin/multi-client.js
client/lib/index.js
client/lib/schemas/multi-client-config.js
core/lib/common/suite.js

Improvements made: 
1. Merge all summaries into one summary JSON file
2. Add skipped stats and summary creation time. 
3. UX: Deleting individual summary files to give a cleaner look in Jenkins
```
[
{
"suite": "Testbot Diagnositcs",
"stats": {
"tests": 4,
"ran": 3,
"skipped": 1,
"passed": 3,
"failed": 0
},
"tests": {
"Flashing an image": "passed",
"Power cycling the DUT": "skipped",
"Is the DUT reachable?": "passed",
"Recording DUT serial output": "passed"
},
"dateTime": "Mon Feb 21 2022 20:38:24 GMT+0000 (Coordinated Universal Time)"
},
{
"suite": "Unmanaged BalenaOS release suite",
"stats": {
"tests": 3,
"ran": 3,
"skipped": 0,
"passed": 3,
"failed": 0
},
"tests": {
"resinos.fingerprint file test": "passed",
"ext4 filesystems are checked on boot": "passed",
"OS-release file check": …
```

patch: Track test skips & summarize the summaries

---

.versionbot/CHANGELOG.yml

Following process outlined here (restricted access):
https://jel.ly.fish/pattern-enable-nested-changelogs-repos-consuming-repo-cf7bcc8

Enable nested changelogs when this project is consumed

---

Makefile
docker-compose.client.yml
docker-compose.qemu.yml

The compose project name is used to prefix all components of the
docker-compose stack, like volumes, networks, containers, etc.
If we are running on Jenkins it would be best to avoid having all builds
using the same default prefix "leviathan-" since they are sharing
a docker host.

makefile: Use Jenkins BUILD_TAG to create unique compose project names

---

client/config/default.js
core/Dockerfile.template
core/entry.sh
core/lib/common/worker.js
core/lib/components/balena/cli.js
docker-compose.client.yml
docker-compose.qemu.yml
suites/config.js
suites/e2e/tests/power-cycle/index.js
worker/Dockerfile.template

Switch to bridge networking for core, client and worker
- avoids all port conflicts when multiple copies of the stack are running on the same host

enable bridge networking for all containers

---

core/lib/common/worker.js

This method currently returns either a promise or a string, which breaks
code expecting a promise. Switch to async, and always return a promise.

core: worker: make ip() async

---

client/bin/multi-client.js
client/bin/single-client.js
client/lib/index.js
core/lib/common/suite.js
suites/e2e/suite.js

Previously, we use to only pass `config` object of the suite config (config.js) to the tests. The journey of this config looks something like this, `multi-client --> single-client --> suite.js (core) --> test.js (core) --> suite.js (of the actual test)`
It's complex and in addition to that confusion, we pass only a part of the config.js. 
Why do this, when you can pass the complete config that the user provided with everything in it and let the core decide what to do with the information? 
This helps in scaling new features and configuration through our config.js in addition to making it super simple for users to read the config available to them to be used in their tests (using `this.suite`)

minor: Transfer complete suiteConfig to core

---

worker/config/default.js
worker/lib/workers/qemu.ts
worker/typings/worker.d.ts

Network configuration, including creating a bridge, setting iptables
rules, and running a DHCP server, requires privileges. This can be done
easily in a container, but would otherwise necessitate running the whole
test suite privileged, or with CAP_NET_ADMIN at least.
Allow users to disable network autoconfiguration in favor of manually
setting up a bridge and DHCP server separately. This allows the suite to
be run unprivileged, if necessary.

worker: qemu: add option to disable network autoconfiguration

---

core/lib/common/suite.js
core/lib/common/suiteSubprocess.js
core/lib/main.js

This is the updated and rebased version of this PR: https://github.com/balena-os/leviathan/pull/607
This PR moves the subprocess specific configuration, signal handling, setup, and teardown into another module, allowing the Suite object to be created and used in other contexts.
@vipulgupta2048 I'm not sure how to document the parameters given to the Suite constructor here, as they're both objects, and I'd like to further clean up and define these parameters in the future.

Suite subprocess

---

client/bin/multi-client.js

this PR https://github.com/balena-os/leviathan/pull/716 broke the multi client. When multiple suites were specific in the `config.js` of the workspace, the client would try to simultaneously run them on the same worker, which led to failure. Examples are here: https://jenkins.product-os.io/job/leviathan-v2-template/500/consoleFull. This lead to the job not even attempting 2/3 suites and ignoring the failures
This happened because the allocated `worker` was removed from the multi client accidentality.

hotfix: client: fix multiple quites on qemu builds

---

core/lib/common/worker.js

Fix sshkey location when sending ssh keys to avoid tunnel failures.
This will be deprecated anyway when the core is moved back to the worker as direct ssh to the DUT will be possible. For now this will just make the new ssh key tests work more smoothly

core: force ssh key location

---

core/config/default.js
core/lib/main.js

No longer needed to be configured using `default.js` configuration file. 

patch: Remove Express server port config

---

Makefile
docker-compose.client.yml

Limit the environment variables passed to the client container by matching any of the following:
```
WORKSPACE
REPORTS
SUITES
DEVICE_TYPE
WORKER_TYPE
BALENA*
```
These can be provided either as an argument to make, or exported to the environment, or pre-written to the .env file.
```bash
$ echo SUITES=/path/to/suites >> .env
$ echo BALENACLOUD_APP_NAME=balena/testbot >> .env
$ make env
WORKSPACE=./workspace
REPORTS=./workspace/reports
SUITES=/path/to/suites
DEVICE_TYPE=genericx86-64-ext
WORKER_TYPE=testbot
BALENACLOUD_APP_NAME=balena/testbot
```
```bash
$ make env SUITES=/path/to/suites BALENACLOUD_APP_NAME=balena/testbot
WORKSPACE=./workspace
REPORTS=./workspace/reports
SUITES=/path/to/suites
DEVICE_TYPE=genericx86-64-ext
WORKER_TYPE=testbot
BALENACLOUD_APP_NAME=balena/testbot
```
```bash …
```

Record environment variables to file for client env

---

Makefile
docker-compose.client.yml
worker/Dockerfile.template
worker/config/default.js
worker/lib/workers/qemu.ts

When KVM is not used we can easily emulate generic-aarch64
on x86_64 hosts so avoid tying the host and target architectures
together in the Makefile.

Do not assume qemu DUT arch will match the host

---

worker/lib/workers/qemu.ts

Log statements for powerOn/powerOff were added for debugging when
refactoring the QEMU worker to operate w/out libvirt. Remove these.

worker: qemu: remove debug print statements

---

core/lib/common/suiteSubprocess.js

This fixes the error:
TypeError: Cannot read property 'state' of undefined

core: suiteSubprocess: replace this.state.log w/ console.log

---

core/lib/common/worker.js

catch error thrown when execute command over ssh fails
This may not fix the errors we are seeing, but will at least provide more information
See: https://github.com/balena-os/meta-balena/issues/2671

catch error in executeCommandInhostOs

---

core/lib/common/utils.js
core/lib/common/worker.js

Catch unhandled errors within `executeCommandOverSSH` function. 
When this function is used during the `reboot` function, there is a high probability that SSH attempts are going to be made while the DUT is offline, or the DUT will drop offline while the SSH connection is active. This can sometimes lead to `node-ssh` and `ssh2` packages throwing various errors, including `unable to exec` and `no response from server`. 
Sometimes, these errors would not be caught and handled - I think it depended on when exactly the DUT went offline/when the attempt to SSH was made. The unhandled error leads to the entire test suite crashing, and a large crashdump of unhelpful logs. 
Here, I've attempted to catch all errors that might occur in the function, and then reject the promise.
Tested with testbot + …

core: catch ssh errors correctly

---

Makefile
core/lib/common/worker.js

Resolves: https://github.com/balena-os/leviathan/issues/792
The rpi3 serial test will be fixed by https://github.com/balena-os/leviathan/pull/786 so as long as we don't see ETIMEDOUT we are good.

patch: Increase timeout of http requests to worker

---

core/lib/common/worker.js

reduce from 300 retries to 30 
Could be more of an aggressive reduction, but lets see how this affects things first
resolves: https://github.com/balena-os/leviathan/issues/793 https://github.com/balena-os/leviathan/issues/787

reduce ssh retries

---

core/lib/common/worker.js
core/lib/components/balena/sdk.js

This reverts commit ca1a9238fd59fb3b46321f36a157021c705d1605.
Reverts: https://github.com/balena-os/leviathan/pull/797

Revert "reduce ssh retries"

---

core/lib/common/worker.js

The executeCommand family of methods default to retrying on failure. In
some cases, such as in the ssh-auth test in the cloud test suite, we
expect failures to happen, and want them to be raised immediately. Other
situations might demand adjusting the number of retries and interval to
fit specific tests. Add a retryOptions object to these methods to allow
for this behavior to be configured.

core: worker: add retryOptions to executeCommand methods

---

docker-compose.qemu.yml

Copied from https://github.com/balena-os/leviathan-worker/pull/21

compose: qemu: enable loopback and metadata devices

---

.gitignore
.gitmodules
core/Dockerfile
core/lib/common/suite.js
core/lib/common/worker.js

Added support for private contracts to enable testing of private device types in Leviathan. This patch doesn't limit the current functionality and add on to it. Anyone needing to use a device type that is available in the private contracts will need to clone it themselves into the core directory. 

minor: Add support for Private Contracts

---

.gitmodules

With the patch #810, we were seeing the following error on pulling the contracts. 
```
➜  leviathan-push git:(master) git submodule update --init --recursive
Submodule 'core/contracts/contracts' (https://github.com/balena-io/contracts.git) registered for path 'core/contracts/contracts'
error: submodule git dir '/home/vipulgupta2048/work/leviathan-push/.git/modules/core/contracts/contracts' is inside git dir '/home/vipulgupta2048/work/leviathan-push/.git/modules/core/contracts'
fatal: refusing to create/use '/home/vipulgupta2048/work/leviathan-push/.git/modules/core/contracts/contracts' in another submodule's git dir
Failed to clone 'core/contracts/contracts'. Retry scheduled
error: submodule git dir '/home/vipulgupta2048/work/leviathan-push/.git/modules/core/contracts/contracts' is inside …
```

patch: Fix contracts name

---

core/lib/common/worker.js

The GET request to the DUT supervisor endpoint has a timeout of 5 seconds  - when doing this request to the tx2 DUT, there is a high chance of this timeout being exceeded, causing the `pushContainerToDut()` function to fail.
Increased it - currently testing it out

increase timeout on local push sv ping

---

docker-compose.qemu.yml
worker/Dockerfile.template

This reverts commit 3b6ce13734e98e981492e01bc874c0a439cb1536.

Revert "worker: Pin to stable release 2.5.10 prior to md support"

---

core/Dockerfile

On x86 we should use the standalone package to save time.
See: https://github.com/balena-os/leviathan/pull/819

On Apple Silicon we should install balena CLI via npm

---

core/lib/components/os/balenaos.js

The testbot AP is visible and is discovered during a scan. Let's remove the hidden attribute as it may cause problems for the 243390-rpi wireless tests.
Changelog-entry: Remove hidden attribute from DUT wireless connection file
Connects-to: https://github.com/balena-os/meta-balena/pull/2802

os/balenaos: Remove hidden attribute from DUT wireless connection file

---

core/lib/common/worker.js

…ss of the DUT
Instead of retrying to get the DUT IP address 120 times on a 1 seconds interval, let's reduce it to 30 times because the resolveLocalTarget itself will timeout too in 15 seconds: https://github.com/balena-os/leviathan-worker/blob/master/lib/helpers/index.ts#L162
So reducing the retries number to 30 will effectly bring the total combined timeout to a maximum of 8 minutes.
Signed-off-by: Florin Sarbu <florin@balena.io>

core: Reduce retries on fetching IP address of DUT

---

core/lib/common/worker.js

During etcherPro testing we witnessed, the current implementation of journalctl command failing. Hence, we came up with a command that potentially would be backward compatible for all versions.
Additionally, timeouts were incorrectly being overridden by the archivelogs helper leading to a timeout of potentially 50 minutes if it fails. Fixed that to do only 3 retires of 5 seconds each. 

patch: Improve archivelogs journalctl command

---

docker-compose.client.yml
docker-compose.qemu.yml

This reverts commit eb69ff445fe0cac4f2060e67fa6994e61c3ca4b9.
Hardcoding the bridge address like this results in conflicts when multiple instances are running on one jenkins node.
A new solution for local workstation testing will have to be considered.

Revert "docker-compose: stop using the default docker bridge"

---

Makefile
core/entry.sh
docker-compose.client.yml
docker-compose.qemu.yml

The `make subnet` command can be called on Jenkins and similar to generate
a unique subnet that is not in use.
The default is a higher-than-default subnet for developer workstations.
The DinD daemon for the core service is also defaulting to a non-default address for the bridge.
See: https://github.com/balena-os/leviathan/pull/842

Avoid conflicting docker subnets

---

Makefile
core/entry.sh
docker-compose.client.yml
docker-compose.qemu.yml

Reverts balena-os/leviathan#856
Jobs are still facing this error and blocked 
```
Successfully tagged jenkins-leviathan-v2-template-9916_core:latest
./bin/docker-compose up --force-recreate --remove-orphans --exit-code-from client
Network jenkins-leviathan-v2-template-9916_default  Creating
Network jenkins-leviathan-v2-template-9916_default  Error
failed to create network jenkins-leviathan-v2-template-9916_default: Error response from daemon: Pool overlaps with other one on this address space
make: *** [Makefile:77: test] Error 1
+ status=FAILURE
+ make down
```
Need to figure out what's going wrong.

Revert "Avoid conflicting docker subnets"

---

.github/renovate.json
docker-compose.qemu.yml

This env var is still used by the leviathan-worker project for e3e tests against draft worker releases.

Restore worker release env var

---

.github/renovate.json

renovate: Remove v prefix from leviathan-worker github-tags

---

core/Dockerfile

This improves stage when changing node dependencies as it won't need to re-install or re-build the CLI stage.
We also need to keep build dependencies in the final image as suites can install npm packages at runtime.

core: Re-order docker build steps to improve caching

---

.github/workflows/flowzone.yml
core/lib/common/worker.js

This is a further attempt to avoid ETIMEOUT errors when running on GH actions and connecting to real testbots.
See: https://github.com/balena-os/leviathan/issues/792

core: Increase the default timeout for worker connections to 30s

---

.github/renovate.json
docker-compose.qemu.yml

Instead the worker e2e suite will use sed to replace the worker release at runtime.
Depends-on: https://github.com/balena-os/leviathan-worker/pull/41

worker: Deprecate the WORKER_RELEASE env var

---

docker-compose.qemu.yml
swtpm/Dockerfile

QEMU is capable of using an emulated software TPM exposed via socket. A TPM is necessary for full disk encryption (FDE), so add a service to provide this to the QEMU worker.

compose: qemu: add swtpm service

---

Makefile
docker-compose.qemu.yml
docker-compose.secureboot.yml

Not all platforms support secure boot, notably aarch64 using tianocore firmware. Additionally, swtpm may not be available for all platforms. Accordingly, move the swtpm service to a separate compose file that is only used when secure boot is enabled.
Fixes: https://github.com/balena-os/leviathan-worker/actions/runs/3842807262/jobs/6745900340

split swtpm service into separate compose file

---

client/package-lock.json
core/package-lock.json

Apparently, only hard deleting the lockfiles without cache will net you the latest nested dependencies. TIL. Updating both core and client's lockfiles to close pending dependabot PRs.
- patch: Update core lockfile
- patch: Update client lockfile

Update lockfiles to get latest nested dependencies

---

client/bin/multi-client.js

Remove try/catch block surrounding client code that blanket handles all exceptions, and makes debugging and log messages worse.
When we don't have a valid way to handle an exception, just throw it. The traceback is more useful than the handler.

client: throw errors instead of blanket handling

---

docker-compose.qemu.yml
docker-compose.secureboot.yml

These are a couple supporting changes necessary for secure boot testing.
The first commit stops the test run from aborting on container exit. The second passes through an environment variable that allows for preconfiguring a flasher image to opt-in to secure boot.

Secure boot testing

---

docker-compose.secureboot.yml

swtpm stores state in the directory specified in the --tpmstate argument
If the same state directory/files are used for multiple installations, the available space can be filled, and the installer will fail with the error "insufficient space for NV allocation".
Move swtpm state to tmpfs to create new state files every run.

swtpm: store state in tmpfs

---

docker-compose.qemu.yml

This bumps the default worker release that is used in the absence  of the `WORKER_RELEASE` env var. Previously it defaulted to 2.6.13, which was prior to several changes that break compatibility to the latest version of the meta-balena test suites. This meant when running locally, without `WORKER_RELEASE` pointing to a more recent release, the tests wouldn't work

update default worker version

---

client/bin/multi-client.js

Would be nice to see the final result in the logs only rather than in another file

patch: Output final-result in the end

---

core/lib/common/worker.js
core/lib/main.js
suites/e2e/package.json
suites/e2e/suite.js
suites/e2e/tests/always-fail/index.js

To reduce Core's dependencies and in the end, simplify Leviathan architecture. We are taking the first steps to use the leviathan test helpers package in the e2e test suite. This will aid in removing Core's helpers #977 and helps provide a testbed to stabilize changes made in the test-helpers package. 

minor: Add Leviathan Test Helpers

---

docker-compose.qemu.yml

This env var breaks parsing by Renovate, and it is no longer used by Jenkins or leviathan-worker e2e.
See: https://github.com/balena-os/leviathan/pull/935
See: https://github.com/balena-os/leviathan/pull/918

Deprecate worker release env var (again)

---

docker-compose.qemu.yml

Whether the internal disk is attached or not will be defined by the environment. This allows to test the migrator that requires booting only the external disk.

docker-compose-qemu: allow to configure internal disk

---

core/lib/common/worker.js
core/lib/main.js
suites/e2e/package.json
suites/e2e/suite.js
suites/e2e/tests/always-fail/index.js

Reverts balena-os/leviathan#976
Reverting this again because we are trying to first solve for Public device URL instability issues that we are facing. This PR can return when things are stable after the leviathan simplification.

Revert "minor: Add Leviathan Test Helpers"

---

core/lib/common/worker.js
suites/e2e/tests/serial/index.js

enable tests to use serial as a comms channel for `executeCommandInHostOS()` instead of ssh.
Refer to this PR for motivations - and notes on the worker side implementation: https://github.com/balena-os/leviathan-worker/pull/63
I have also had to disable the test that reads the serial output that is written to a textfile for the qemu worker - to be replaced with an actual serial console test - but to get the worker PR merged, first I had to disable the test here

core: enable serial executeCommandinHostOS

---

core/lib/common/worker.js
core/lib/components/balena/sdk.js
suites/e2e/suite.js

The cloud and worker objects can now be initialised with an sshConfig 
```js
sshConfig: {
host: 'ssh.devices.bm.balena-dev.com',
port: '222',
}
```
which can be added to the suites `config.js` and passed through to these objects in the test suite

core: allow for balena machine ssh target

---

core/package.json

Jekyll build failing is leading to new docs not publishing. Stopping GH Jekyll builds.

patch: Add .nojekyll file to docs

---

core/lib/components/balena/sdk.js

We have an issue with our BM builders where pushes to x86 fleets fail. This workaround (adding the no cache flag) seems to resolve it. If we can't resolve the real issue then we can use this for now.

add nocache flash to balena push

---

client/lib/balena.js
client/lib/schemas/multi-client-config.js

enable the client to search multiple apps for an appropriate worker. Needed as we have autokits of multiple architectures now so they must be in different apps.
Hopefully non-breaking as we still support providing one app as a string

client: enable searching multiple apps for worker

---

core/lib/common/worker.js

This is a change to be paired with https://github.com/balena-os/leviathan-worker/pull/91 to try to reduce the risk of connection drops while streaming the OS images to the worker. For larger images, especially when preloaded, the connection is prone to timing out. These PR's attempt to remove the http request and server timeouts. 
The seperate heartbeat timeout that we have will timeout the test run if something goes wrong. 

core: remove request timeout on flashing

---

core/lib/common/worker.js

This is an attempted fix for the following problem:
- most tests are failing with the latest meta-balena unmanaged test suite at the final test
- the connection seems to just timeout - when looking at a device in the stuck state I saw thousands of stale socat+ssh processes
- I added a timeout to the command to close these after they've been open a long time 
Seems to fix the problem - not a great fix but all tests are blocked at the moment

add timeout netcat processes

---

client/lib/balena.js
client/lib/config-validator.js

PR to add Config.js Validator #1079 missed a step to authenticate the SDK to access private contracts and validate fields for private device types, which led to errors. This PR resolves that. 

patch: Authenticate the validator before validation

---

.github/workflows/flowzone.yml
action.yml

The first draft of the Leviathan GHA gaining feature parity to Jenkins leviathan-v2-template but with seperate test jobs in the matrix. Refer to test.yml
Fibery: https://balena.fibery.io/Work/Project/Create-a-GitHub-Action-workflow-for-Leviathan-builds-248

minor: Add leviathan GitHub Action

---

client/Dockerfile

Patch to resolve reliablity of Alpine packages being installed as part of client Dockerfile on GitHub Actions. 
This is fix is a best effort resolution to the the issue that we were facing. After implementing the fix, we didn't face the same after 6 retries of the job. 

Client: Update alpine packages before installing packages

---

core/pagesconfig.json
documentation/debugging.md
documentation/quickstart-autokit.md
documentation/quickstart-qemu.md

Fixing the endpoint name in debugging docs that queries state of the autokit at any given time.

Docs: Fix endpoint name from s/status/state

---

documentation/learn-more.md

This happenned because of it: https://balena.zulipchat.com/#narrow/stream/345885-aspect.2Fsecurity/topic/Share.20request.20for.20.22Testbots.20and.20the.20story.20so.20far!.22/near/442340747, so to reduce noise getting rid of the link. 

patch: Remove internal presentation link to testbot

---

suites/e2e/suite.js
suites/e2e/tests/power-cycle/index.js
suites/e2e/tests/serial/index.js

Upgrading the e2e test suite to latest changes from the meta-balena OS test suite
1. Remove unwrap functionality: https://github.com/balena-os/meta-balena/pull/2974
2. Add systemd feature for services
3. Add new tests to check if the device is working properly
4. Add support for different device types
5. Readability improvements
And more!

Add migration & secureboot options to e2e test suite

---

core/lib/common/worker.js

the function that was being used to fetch the DUT ip from the worker had nested retries that led to 30x5 = 150 retries, and timeouts taking ~40 mins in the case the DUT wasn't reachable (autokit setup fault, device not booting, problem during flashing). This removes the nested retries and reduces the retries to 50 /  ~ 10mins

remove nested retries in getDutIp function

---

core/Dockerfile
core/lib/common/worker.js

we were previously using CLI 16.0.0, which is now over 365 days since the next major release (17.0.0) , so its deprecated and won't work without adding the --unsupported flag, or updating. Choosing to update

core: update CLI to 19.0.0

---

docker-compose.client.yml
docker-compose.qemu.yml

This volume is used to share qemu's QMP socket between the worker and core containers, allowing tests to connect, receive events from, and control qemu.

compose: map qemu volume into worker

---

action.yml

This is to avoid calshes of artifact names when running a test matrix with the secureboot option enabled

add secureboot identifier into report name

---

action.yml

makes sure we generate a report name even if tests fail

add if: always() to report name generation

---

core/lib/common/worker.js

When the worker is in production mode, ssh auth when creating the reverse tunnel to tunnel though it to the DUT failed. Using BC username auth with BC registered keys fixes it
tested on a prod worker with unipi3 DUT
resolves https://github.com/balena-os/leviathan/issues/1191

core: ssh tunnels: fix auth errors when worker is in prod mode

---

client/bin/multi-client.js

When FLASHER_SECUREBOOT=1 select only devices that have a `deviceType-sb` tag, taking into account the device type name could already have a `-sb` suffix.

Extend selection of devices to run secureboot tests

---

Makefile
docker-compose.qemu.yml

'docker compose up' will build any missing images,
but does not accept build-args from the command line
instead, we want to always inherit some build args
from the environment via docker compose substitution

Ensure we always pass the BALENA_ARCH worker build arg

---

core/Dockerfile
docker-compose.client.yml

These contracts used to be copied to the core service at build time if private device types cloned the repo before running test suites.
However, since switching to pre-built images by default we need to manually mount private contracts to the core service.

Bind mount private contracts in the core service

---

core/lib/common/worker.js

The total flashing time used to be:
30 tries × 25 seconds = 750 seconds (12.5 minutes)
This used to be on the limit of timeout for slowish SD cards and secure boot flashers that need to boot and re-program
It's now double that time:
60 tries × 25 seconds = 1,500 seconds (25 minutes)

worker: extend total flashing timeout to 25 minutes
