balena-os/leviathan

.gitignore, Dockerfile, package.json, src/lib/image.js, src/main.js, src/mocha.opts, src/resin/application.js, src/resin/container.js, src/resin/device.js, src/setup.js, user.json
=> Initial testing framework to master

package.json, src/mocha.opts, src/resin/device.js
=> Globally increase tests timeouts

.eslintrc.yml, package.json, src/lib/image.js, src/main.js, src/resin/application.js, src/resin/container.js, src/resin/device.js, src/setup.js
Run the linter with the following command:
```
npm test
```
Fixes: https://github.com/resin-os/resinos-tests/issues/12
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> Add ESLint

src/components/resinio/sdk.js, src/lib/image.js, src/main.js, src/resin/application.js, src/resin/container.js, src/resin/device.js, src/setup.js, user.json
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> Remove most global variables

Makefile, entry.sh, lib/components/resinio/sdk.js
=> Various fixes

lib/main.js
Change-type:minor
Signed-off-by: Horia Delicoti <horia.delicoti@gmail.com>
=> Use contracts to get the arch version and led property of the device

lib/main.js, scripts/format.js, scripts/pensieve.js
=> Fix pensieve output

Makefile, lib/components/resinio/sdk.js, lib/main.js, lib/utils.js, lib/workers/qemu.js, package.json, tests/bluetooth-test.js, tests/device-online.js, tests/device-reportOsVersion.js, tests/enter-container.js, tests/hdmi-uart5.js, tests/hostapp-update.js, tests/identification-led.js, tests/kernel-splash-screen.js, tests/os-file-format.js, tests/push-container.js, tests/push-multicontainer.js, tests/reboot-with-app.js, tests/reload-supervisor.js, tests/resin-device-progress.js, tests/resin-splash-screen.js, tests/resin-sync.js, tests/rpi-serial-uart0.js, tests/rpi-serial-uart1.js, tests/service-variables.js, tests/update-supervisor-through-api.js
=> Fix the way we handel unhandledRejection for the qemu worker

lib/utils.js
=> Retry SSH connection if connection drops internally

lib/components/resinio/sdk.js, lib/main.js, lib/runner.js, lib/utils.js, tests/push-container.js, tests/push-multicontainer.js
Includes automated multi container application test.
=> Re-work the way we push code 

lib/utils.js
=> Trim ssh output

lib/components/resinio/sdk.js, tests/reload-supervisor.js
=> Automate supervisor update testcase

tests/update-supervisor-through-api.js
=> Automate supervisor update through the api

lib/components/resinio/sdk.js, tests/resin-device-progress.js
Closes #240 
[FD](https://www.flowdock.com/app/rulemotion/r-beginners/threads/uQTzUXO5OtXAR9deYHMhcqewqzx) discussion about resin-device-progress
=> Automate resin-device-progress test

README.md
=> Revamp the README and remove outdated information

Makefile
=> Fix multiple parallel runs on the same machine

lib/workers/testbot.js, package.json
=> Add support for testbot infrastructure

lib/utils.js, tests/push-container.js, tests/push-multicontainer.js
=> Factor out common push code

lib/main.js, lib/scripts/options.js, lib/utils.js
=> Parameterize worker as a top level option

lib/components/balena/sdk.js, package.json, tests/update-supervisor-through-api.js
=> Use internal balena-requests for API calls

tests/os-file-format.js
=> Fix the filename expected from the image maker

lib/main.js, tests/bluetooth-test.js
[relevant commit](https://github.com/balena-io/balena-tests/commit/e75605002fc3475795836549272aecca357f2bf6)
=> Fix balena component due to providing a new component

tests/reload-supervisor.js
Relevant [commit](https://github.com/balena-os/meta-balena/commit/5ae0b5fb1c781af381872325bb9c15ceca490976)
=> Update reload supervisor test due to balena rename

README.md
=> README.md: Add documentation on running the framework

suites/testlodge/testlodge.tests/i-no-deltas.js, suites/testlodge/testlodge.tests/i-persistent-logging.js, suites/testlodge/testlodge.tests/i-provision-with-deltas.js, suites/testlodge/testlodge.tests/i-with-deltas.js
Signed-off-by: Theodor Gherzan <theodor@balena.io>
=> Fix some formatting issues.

client/index.js, client/package-lock.json, client/package.json, core/lib/common/utils.js, core/lib/common/worker.js, core/lib/main.js, core/package-lock.json, core/package.json
Signed-off-by: Theodor Gherzan <theodor@balena.io>
=> Implement artifact caching

.github/MAINTAINERS
Signed-off-by: Gergely Imreh <gergely@balena.io>
=> Add MAINTAINERS file

core/lib/common/suite.js
Before the change, the process was hanging awaiting IPC messages.
=> Fix hanging suite process

client/bin/multi-client.js
Can be used to run the client from CI jobs.
=> Add non-interactive mode

client/bin/multi-client.js
=> Fix run from non-bin director

suites/os/suite.js, suites/os/tests/fingerprint/index.js
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
=> Add OS fingerprint test

suites/os/suite.js, suites/release/suite.js
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
=> Rename managed and unmanaged test suites

client/bin/multi-client.js, workspace/run-tests.sh
=> Ensure host network is used in the container

.balena/balena.yml, .dockerignore, .gitignore, worker/Dockerfile.template, worker/lib/index.ts, worker/lib/workers/testbot.ts, worker/package-lock.json, worker/package.json, worker/typings/worker.d.ts
So we use the same logic we test with e2e tests of the SDK.
=> Start using testbot SDK in leviathan

client/bin/multi-client.js, client/lib/index.js, core/lib/main.js
=> Report suite results back to the client

client/lib/index.js, client/package-lock.json, client/package.json
=> Add basic retry logic to client->core communications

suites/os/tests/fingerprint/index.js
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
=> Reword fingerprint test assertions for consistency

worker/Dockerfile.template
=> Pin glider version to avoid build issues

client/Dockerfile, client/bin/multi-client.js, client/entry.sh, workspace/.gitignore, workspace/run-tests.sh
=> Store test report per worker device

client/bin/multi-client.js
The previous version was incorrectly triggering the download from
the signal handlers, which was not doing anything in the case of normal
process completion.
=> Fix DUT serial output download logic

.lintstagedrc, client/.dockerignore, client/.gitignore, client/Dockerfile, client/bin/multi-client.js, client/entry.sh, client/jest.config.js, client/lib/balena.ts, client/package-lock.json, client/package.json, client/test/balena.test.ts, client/tsconfig.json, package-lock.json, package.json
It also adds ability to write TS in the client code.
=> Add device info to reports file name

lib/utils.js
Signed-off-by: Florin Sarbu <florin@resin.io>
=> utils.js: Fix ssh to devices

core/lib/main.js, suites/os/tests/config-json.js, suites/os/tests/fingerprint/index.js
- Solves #356 
- Fixes a spelling mistake and improves test message on successful fingerprint test.
- Updates url.parse method with the new URL constructor - https://nodejs.org/api/url.html#url_new_url_input_base
=> Add integrity check on file uploads

core/lib/main.js, suites/os/tests/config-json.js, suites/os/tests/fingerprint/index.js
Reverts balena-os/leviathan#359
=> Revert "Add integrity check on file uploads"

.balena/balena.yml, README.md, compose/balena.yml, docker-compose.yml, worker/Dockerfile.template, worker/package-lock.json, worker/package.json, workspace/.gitignore
- Removes private package limitation
- Patch breaking builds 
- Update dbus package
- Update glider dependency
Todo:
=> Patch breaking releases

core/lib/common/worker.js, core/lib/components/os/balenaos.js, suites/os/conf.js, suites/os/suite.js, worker/Dockerfile.template, worker/lib/index.ts, worker/lib/workers/testbot.ts, worker/package-lock.json, worker/package.json
The new testbot SDK is suitable for Intel NUC DUT.
=> Update testbot library to support more device types

core/lib/main.js
=> increase upload timeout from 5 to 10 mins

documentation/Getting-started.md
=> move getting started leviathan guide here

core/lib/components/os/balenaos.js
Signed-off-by: Robert Günzler <robertg@balena.io>
=> Add unpack type that only unzips

client/bin/multi-client.js
We had several instances of the client sending multiple jobs to the same worker - this was because the client would create a child process to send the job to a found idle worker, and if it got to the next iteration of the loop before the worker had a chance to update its status to busy, it would see the worker as idle and send the next job to it too
This fix adds an array to the client to track workers that it has started jobs on, to prevent the client from ever sending multiple jobs to the same worker. When a child process running a particular job exits, the worker is removed from this array. 
=> stop client sending multiple jobs to same worker

client/bin/multi-client.js
Signed-off-by: Robert Günzler <robertg@balena.io>
=> multi-client: catch exceptions of the single-client children

core/lib/common/worker.js, core/lib/components/balena/sdk.js
Adding 
````
* Standardized Helpers needed
* 
* FetchOS() - Downloads version of OS that you provide it with, if not downloads default dev balenaOS version using balenaSDK 
* 
* Reboot helper - Reboots the DUT and waits until it is reachable again
```
=> Add common suite helpers to Leviathan 

README.md
=> Fix balenaOS image link in README

README.md
=> Replace broken link and fix readme formatting

worker/lib/workers/testbot.ts, worker/package-lock.json
=> bump testbot sdk package to support fin

.dockerignore
Update: 
Will update the CLI version in the core, after the armv7 blockers have been solved. 
Context: https://www.flowdock.com/app/rulemotion/p-testbot/threads/fsdypCCB26VorkBxBuY_MTZMqAp
=> patch: Add docs/ to .dockerignore

client/bin/multi-client.js, client/lib/reporter.js
=> hotfix: wait for report stream to end before exit

core/lib/common/worker.js
=> patch: Reduce timeout interval retrying archiveLogs helper

core/lib/common/worker.js
=> core: fix typo of retrieve

.dockerignore
From: https://stackoverflow.com/a/53240012/8522689
=> patch: Update .dockerignore

core/lib/common/suite.js
=> add title to json summary

worker/Dockerfile.template
=> patch: Install git in the worker for npm dependencies

.github/dependabot.yml, .github/workflows/balena-ci.yml, .github/workflows/balena.yml
@rcooke-warwick  Adding the API key of the testbot user account.
=> patch: Create balena-ci.yml

Makefile, worker/lib/workers/qemu.ts
=> Add detached target to makefile for running in jenkins

Makefile
=> Fix ordering of docker-compose args

worker/lib/workers/testbot.ts, worker/package.json
Signed-off-by: Alexandru Costache <alexandru@balena.io>
=> Add RevPi Core 3

worker/package-lock.json
See: https://github.com/balena-os/leviathan/pull/549
=> worker: update package-lock

worker/lib/workers/qemu.ts
QEMU is able to optionally use OVMF firmware, built from Tianocore edk2,
to support UEFI. QEMU can be told to load OVMF firmware using a number
of methods, not all of which fully support persistent UEFI variables,
such as are required by secure boot.
Switch from using the -bios flag to fully emulated pflash to load OVMF,
including support for persistent UEFI variables. Also switch from the pc
machine to q35, which is required for fully emulated pflash.
https://github.com/tianocore/edk2/blob/e1e7306b54147e65cb7347b060e94f336d4a82d2/OvmfPkg/README#L65
=> qemu: switch to emulated pflash to support UEFI vars

core/Dockerfile.template, core/package-lock.json, core/package.json
This also removes some big build dependencies that were leftover
in the final build stage.
```
[Info]     ┌─────────┬────────────┬───────────────────────┐
[Info]     │ Service │ Image Size │ Build Time            │
[Info]     ├─────────┼────────────┼───────────────────────┤
[Info]     │ core    │ 731.17 MB  │ 7 minutes, 1 second   │
[Info]     ├─────────┼────────────┼───────────────────────┤
[Info]     │ worker  │ 770.35 MB  │ 6 minutes, 15 seconds │
[Info]     └─────────┴────────────┴───────────────────────┘
```
=> Install balena CLI via package-json 

core/Dockerfile.template, core/entry.sh, worker/Dockerfile.template, worker/entry.sh
```
[Info]     ┌─────────┬────────────┬─────────────────────┐
[Info]     │ Service │ Image Size │ Build Time          │
[Info]     ├─────────┼────────────┼─────────────────────┤
[Info]     │ core    │ 569.02 MB  │ 21 seconds          │
[Info]     ├─────────┼────────────┼─────────────────────┤
[Info]     │ worker  │ 414.44 MB  │ 1 minute, 9 seconds │
[Info]     └─────────┴────────────┴─────────────────────┘
```
=> Change base images from debian to alpine

worker/lib/workers/testbot.ts, worker/package.json
Signed-off-by: Alexandru Costache <alexandru@balena.io>
=> Add CM4 IO-Board

client/Dockerfile, client/entry.sh, docker-compose.local.yml
Changes to make it easier for Jenkins to run the client in a container.
=> client: Change base image to alpine

client/bin/multi-client.js, client/package-lock.json, client/package.json
=> patch: Update balena-sdk to 16.3.0

.github/workflows/balena-ci.yml
=> patch: Add deploy to balena action

worker/lib/workers/qemu.ts
=> workers: qemu: enable serial logging

Makefile, docker-compose.local.yml, worker/Dockerfile.template, worker/entry.sh, worker/lib/workers/qemu.ts
One think I'd like to look into further is if the Makefile `$(COMPOSEBIN)` target is getting executed even when the target file already exists, as it prints a message every time.
=> Make KVM support optional

.github/workflows/balena-ci.yml
Avoid pinning to master as we don't want to pick up breaking changes.
=> Update deploy-to-balena-action to v0.5.4

README.md, balena.yml
=> minor: Add deploy with balena button to README

client/package-lock.json, client/package.json, core/lib/components/balena/sdk.js, core/package-lock.json, core/package.json, worker/package-lock.json, worker/package.json
Resolves: https://github.com/balena-os/leviathan/issues/576
=> Update balena-cli and balena-sdk

core/lib/components/balena/sdk.js
=> core: update cloud helpers after sdk bump

Makefile, docker-compose.client.yml
=> client: Export additional env vars required for cloud suites

core/Dockerfile.template, core/entry.sh
Context: https://www.flowdock.com/app/rulemotion/p-testbot/threads/ZU9ant6-VdGwrp7mzEn5WVn13NZ
=> patch: Resolve nodeJS pkg installation issue for core

client/lib/index.js, core/Dockerfile.template, core/entry.sh, worker/Dockerfile.template
=> patch: Throw errors on upload

worker/Dockerfile.template, worker/package-lock.json, worker/package.json
=> bump testbot sdk for fin fix

worker/Dockerfile.template
=> worker: fix build on x86

suites/config.js
=> patch: Add config.js for e2e suite

core/lib/common/graphics.js, core/lib/common/suite.js, core/lib/common/worker.js
=> core: Re-enable tslint features that were disabled

worker/lib/index.ts
Also fix a misspelled property caught by the TS compiler.
=> worker: fix TS2571 errors when importing into TS module

worker/lib/index.ts
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>
=> Fixes issue with importing lockfile module

suites/e2e/suite.js
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>
=> Adds package for util to e2e suite.js

Makefile, docker-compose.qemu.yml, worker/Dockerfile.template, worker/lib/helpers/index.ts, worker/lib/workers/qemu.ts, worker/package-lock.json, worker/package.json
See: https://github.com/balena-os/meta-balena/issues/2554
=> Enable aarch64 QEMU workers

core/lib/components/os/balenaos.js, core/package-lock.json, core/package.json
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>
See: https://github.com/balena-os/meta-balena/issues/2554
=> Updates resin-image-fs to balena-image-fs for ARM64 compatibility

docker-compose.qemu.yml
=> Remove deprecated env var SKIP_INSTALL_BINARY

.github/workflows/balena-ci.yml
=> Update deploy-to-balena action to v0.10.7

core/lib/components/os/balenaos.js
=> core: fix reading os-release for flasher images

suites/README.md, suites/e2e/suite.js
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>
=> Fixes spelling and grammar in e2e

worker/lib/workers/qemu.ts
=> workers: qemu: fix vars path for x86_64

core/Dockerfile
Bump Node 12.19.1 to 14.19.3 in core
=> core: bump node 12 -> 14

docker-compose.qemu.yml
=> worker: Expose additional QEMU runtime args via docker-compose

core/lib/common/worker.js
Create a directConnect variable that indicates whether we're connecting
to a local instance of the worker server, including if the connection is
over a unix domain socket. This allows the suite to skip steps that
don't pertain to local runs.
=> core: worker: handle all local connections the same

.github/workflows/e2e.yml, Makefile, docker-compose.qemu.yml, suites/config.js, worker/Dockerfile.template
Depends-on: https://github.com/balena-os/leviathan/pull/786
=> Run QEMU and testbot e2e tests via github-actions

core/config/default.js, core/lib/common/suiteSubprocess.js, core/lib/common/worker.js, suites/config.js, suites/e2e/tests/power-cycle/index.js, suites/e2e/tests/serial/index.js
Todo
- Add a serial pull or an explicit test for each suite to pull the serial for testbot workers. 
- Check if this unblocks GitHub actions progress. 
=> minor: Improve e2e serial test for Leviathan v2

Makefile
Resolves: https://github.com/balena-os/leviathan/issues/795
=> Makefile: Fix unique container names when running on Jenkins

core/lib/common/worker.js
=> core: Reduce logging in failed SSH attempts

core/lib/common/suiteSubprocess.js
resolves https://github.com/balena-os/leviathan/issues/811
When a device type was passed to the suite that wasn't in the publicly available device types contracts, the suite would fail in the constructor. The error was never caught and the suite subprocess would exit with a zero, leading to the suite passing. 
I added a try/catch to catch the error and exit with a failure if it happens
=> core: exit with failure if suite doesn't start

core/lib/common/taskQueue.js
=> Fix "Declaration emit" error during `npm run docs`

.gitmodules, core/.dockerignore, core/Dockerfile, core/lib/common/suite.js
See: https://github.com/balena-os/leviathan/pull/810
=> core: Move contracts submodule back to original path

core/lib/components/balena/cli.js
Removing helpers as mentioned on this sheet: https://docs.google.com/spreadsheets/d/1AAQ8h-bAJJVV1iNNHlHOIPH5Dum2rxGwWgLBWMg_Uw8/edit#gid=846854747
=> patch: Remove unused CLI helpers

core/lib/components/balena/sdk.js
=> patch: Remove unused SDK helpers

Makefile
Convert Darwin to lowercase and arm64 -> aarch64 as needed.
=> Add conditions for Apple Silicon workstations

docker-compose.client.yml, docker-compose.qemu.yml
This causes problem when running locally in QEMU.
=> Stop using the default docker bridge

.github/workflows/flowzone.yml
=> Enable external contributions via flowzone

core/lib/components/balena/sdk.js
=> add logging and timeout to balena push

.github/renovate.json
=> renovate: Inherit settings from balena-io/renovate-config

.github/renovate.json
=> Fix renovate extends syntax to include balena-io config

core/lib/common/worker.js
Resolves: https://github.com/balena-os/leviathan/issues/792
=> Add retries to some worker requests

.github/renovate.json
=> renovate: Disable automerge for major and minor updates

client/Dockerfile, client/package-lock.json, package-lock.json
=> patch: Upgrade client to v18

docker-compose.qemu.yml
=> docker-compose: qemu: remove dep on swtpm

documentation/quickstart-qemu.md, documentation/quickstart-testbot.md, documentation/quickstart.md
=> patch: Improve Getting Started instructions

core/lib/common/suite.js
Read the suite configuration for the force migration flag which configures the flasher image to force an installer migration.
=> suite: add installerForceMigration configuration

core/lib/common/suite.js
=> suite: move installer configuration to balenaOS configuration section

core/Dockerfile
See: https://github.com/balena-io/balena-cli/pull/2616
=> Update balena-cli to v16.1.0 with arm64 binaries

documentation/quickstart-qemu.md, documentation/quickstart.md
Improving the QEMU guide on basis of feedback received. 
=> patch: Update QEMU getting started guide

client/bin/multi-client.js, client/config.js, client/lib/balena.js, client/lib/index.js
To improve short-term reliablity, Leviathan will be working with a seperate balenaMachine. Changes include: 
1. Client improvements to use balena API URL from the config.js  
=> minor: Make Leviathan work with different balenaCloud environments

suites/.prettierrc, suites/e2e/suite.js, suites/e2e/tests/always-fail/index.js, suites/e2e/tests/flash/index.js, suites/e2e/tests/power-cycle/index.js, suites/e2e/tests/serial/index.js, suites/package-lock.json, suites/package.json
Identified vulnerabilities due to deprecated eslint packages in Leviathan suites. Updated the packages and resolve issues.
=> patch: Fix critical vulnerabilities in suites

README.md, documentation/quickstart-autokit.md, documentation/quickstart.md
=> improve autokit quickstart

.github/renovate.json
=> Remove custom automerge rules and use the inherited rules

README.md, core/pagesconfig.json, documentation/quickstart-qemu.md
=> patch: Resolve dead links in README

documentation/config-reference.md, documentation/quickstart-autokit.md, documentation/quickstart-qemu.md, documentation/quickstart-testbot.md
- Clarifies env variables, adds a table for it 
- Add more information on `organization` and `API key` config properties
=> patch: Clarify env variables in Documentation

client/package-lock.json, client/package.json
=> patch: Update client dependencies

core/lib/common/worker.js, documentation/config-reference.md
Add support for local autokit support with IP address
=> Add local autokit support

core/lib/components/os/balenaos.js
=> add jetson-agx-orin-devkit resin-boot index

core/lib/common/worker.js
This PR https://github.com/balena-os/leviathan/pull/1098 failed to resolve the issue with the ssh connection to the DUT failing at the end of the test suites. The exact reason is still unknown but restarting the socat tunnel unstuck the tests. There was some unexpected behaviour with the socat command being used to forward the DUT ports, so instead I've tried to replace it with balena tunnel + standalone port forwarding using `ssh`
Explanation:
Instead of using:
`socat tcp-listen:22222,reuseaddr,fork "system:ssh <USER>@<BALENA_SSH_PROXY> -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/id host <WORKER_UUID> timeout 600 /usr/bin/nc localhost <WORKER_PORT>"` to set up port forwarding from the worker to the core container, and then doing the same on the worker to …
=> replace socat method for ssh tunneling with balena tunnel + ssh tunnel commands

client/bin/multi-client.js, client/lib/balena.js, client/lib/config-validator.js, documentation/debugging.md
After the feedback from customers, it seems having a validator utility that actually checks inputs provided on runtime in the config.js could be beneficial. This provides helpful error that users can understand and help in debugging what the actual issue could be.  
=> Add Config.js Validator

documentation/quickstart-autokit.md
=> ad extra autokit setup information, and basic troubleshooting

core/lib/components/os/balenaos.js
so that the config.json can be injected in the right partition
=> core/lib/components: Specify Jetson Xavier boot partition indexes

.github/workflows/flowzone.yml, suites/config.js
=> patch: Replace environment switcher in e2e config.js

docker-compose.client.yml, docker-compose.qemu.yml
=> allow for secureboot flasher env var for non-qemu runs

action.yml
=> Always upload reports, especially when tests fail

.github/renovate.json, Makefile, docker-compose.qemu.yml, worker/Dockerfile
=> Make leviathan worker ref configurable via env var

action.yml
Added retention and compression setting to upload artifact step in Leviathan, 
Inspiration: https://github.com/balena-os/balena-yocto-scripts/pull/487/
=> patch: Add retention & compression to Leviathan action artifacts

core/lib/components/os/balenaos.js
Connects-to: https://github.com/balena-io-hardware/autokit-interface-sw/pull/98
=> lib/components: Add partition index for Jetson TX2 NX types

client/bin/multi-client.js
Print fleets and worker tag used for device selection.
=> Improve device selection logs

.github/workflows/flowzone.yml, Makefile
Instead just check the installed version of compose for compatibility.
Depends-on: https://github.com/balena-os/yocto-dev/pull/160
=> Remove custom compose binary installation from Make

core/lib/components/os/balenaos.js
=> core/lib: Specify partition indexes for Jetson Nano eMMC and JN30B Nano

.github/workflows/flowzone.yml, Makefile, action.yml, docker-bake.hcl, docker-compose.client.yml
We want to allow image reuse at test time and avoid always building from scratch.
See: https://balena.fibery.io/Work/Improvement/Publish-core-and-client-container-images-2943
=> Publish core and client docker images to ghcr.io

core/lib/common/worker.js
Switch to worker endpoints that allow for initiation -> polling to flash the DUT - reducing drastically the amount of time the socket over public URL needs to remain open
https://balena.fibery.io/Inputs/Pattern/Debugging-BalenaOS-Testing-Leviathan-GHA-Autokit-Common-Issues-4777
Leviathan worker PR: https://github.com/balena-os/leviathan-worker/pull/150
=> Core: worker: use polling to track flashing

core/lib/common/worker.js
This change is based around using the native `fetch` library to send the image to the worker, as the error handling with the deprecated request-promise library just didn't seem to work with node 22.
=> Core: worker: update flashing method to use native fetch API
